# Generated by Django 4.2.7 on 2023-11-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="confirmed",
            field=models.BooleanField(default=False, verbose_name="bestätigt"),
        ),
    ]
